### PR TITLE
Fix two little bug.

### PR DESCRIPTION
**Pull request by charlestang**

### CODE REVIEW

**Comment by amaiorano** [comment]
Hi! First of all, thank you for your contribution. Before merging this, can you please update the commit message to include exactly what you're fixing here, along with examples? This will make it easier to understand this commit in the future. 

Cheers!

**Comment by charlestang** [comment]
Generated link will not work fine, when title contains underline symbol (_)  and back tick symbol (`).

**Review by amaiorano — CHANGES_REQUESTED** [review]
Please replace "Fix two little bug." with "Fix when title contains underline symbol (_) and back tick symbol (`)" in the commit message, amend your commit and push here. Thanks!

**Comment by charlestang** [comment]
Commit message was changed.

**Comment by amaiorano** [comment]
Thank you!

**Pull request merged**
